// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg-hoBUae1POJwNRTJrg7uQM_RSh92B8M',
    appId: '1:61711600724:web:02e29d2ff42f87ccaa31c1',
    messagingSenderId: '61711600724',
    projectId: 'easygo-5c897',
    authDomain: 'easygo-5c897.firebaseapp.com',
    storageBucket: 'easygo-5c897.firebasestorage.app',
    measurementId: 'G-PG65568DTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZum1DZO0yL7GRcTKZb4AIJ6_Edo2mHTs',
    appId: '1:61711600724:android:58d0714cba015eeeaa31c1',
    messagingSenderId: '61711600724',
    projectId: 'easygo-5c897',
    storageBucket: 'easygo-5c897.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwvm3hHUQxtFrQEVekpGMpNHqZE89aCV8',
    appId: '1:61711600724:ios:86cafc1144ec2068aa31c1',
    messagingSenderId: '61711600724',
    projectId: 'easygo-5c897',
    storageBucket: 'easygo-5c897.firebasestorage.app',
    iosBundleId: 'com.example.easygo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwvm3hHUQxtFrQEVekpGMpNHqZE89aCV8',
    appId: '1:61711600724:ios:86cafc1144ec2068aa31c1',
    messagingSenderId: '61711600724',
    projectId: 'easygo-5c897',
    storageBucket: 'easygo-5c897.firebasestorage.app',
    iosBundleId: 'com.example.easygo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg-hoBUae1POJwNRTJrg7uQM_RSh92B8M',
    appId: '1:61711600724:web:ed48dce00e877874aa31c1',
    messagingSenderId: '61711600724',
    projectId: 'easygo-5c897',
    authDomain: 'easygo-5c897.firebaseapp.com',
    storageBucket: 'easygo-5c897.firebasestorage.app',
    measurementId: 'G-F791531KHP',
  );
}
